sudo: required
dist: trusty
language: node_js
node_js:
  - "8"

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
  - export PATH=$PATH:$HOME/.cargo/bin
  - rustup target add wasm32-unknown-unknown
  - rustc -V

script:
  - yarn test
