language: node_js
node_js:
  - "8"

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s
  - rustup update nightly
  - rustup target add wasm32-unknown-unknown --toolchain nightly

script:
  - yarn test
